name: Build, Scan, and Push Docker Image

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 3: SonarQube scan (SonarCloud)
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: app 
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Step 3: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/nodejs-toy-app:latest .
      
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/download/v0.32.1/trivy_0.32.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.32.1_Linux-64bit.deb
      
      # Step 6: Run Trivy image scan
      - name: Scan Docker image with Trivy
        run: |
          trivy image ${{ secrets.DOCKER_USERNAME }}/nodejs-toy-app:latest

      # Step 7: Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 8: Push Docker image to Docker Hub
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-toy-app:latest


