name: CI/CD Pipeline
on: 
    push:
        branches: master

jobs: 
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    # Step 2: Run SonarQube scan (SonarCloud in this case)
    - name: SonarQube scan
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        projectKey: nodejs-toy
        organization: nodejs-toy
        token: ${{ secrets.SONAR_TOKEN }}