name: Build, Scan, and Push Docker Image

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 3: SonarQube scan (SonarCloud)
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: app 
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


