name: CI/CD Pipeline
on: 
    push:
        branches: master

jobs: 
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0