name: Build, Scan, and Push Docker Image

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 3: SonarQube scan (SonarCloud)
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} //Sonar Token generated 
          SONAR_HOST_URL: https://sonarcloud.io
          with:
            projectBaseDir: app/

